/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  CallContractParams,
  CallContractResult,
  Contract,
  ContractEvent,
  ContractFactory,
  ContractInstance,
  ContractState,
  EventSubscribeOptions,
  EventSubscription,
  HexString,
  TestContractParams,
  TestContractResult,
  callMethod,
  fetchContractState,
  getContractEventsCurrentCount,
  multicallMethods,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
} from "@alephium/web3";

import { default as ShinyTokenContractJson } from "../ShinyToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace ShinyTokenTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  ShinyTokenInstance,
  ShinyTokenTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as ShinyTokenTypes.Fields;
  }

  at(address: string): ShinyTokenInstance {
    return new ShinyTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParams<ShinyTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<
        TestContractParams<ShinyTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<
        TestContractParams<ShinyTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParams<ShinyTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
    transfer: async (
      params: TestContractParams<
        ShinyTokenTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "transfer", params);
    },
    destroy: async (
      params: TestContractParams<ShinyTokenTypes.Fields, { to: Address }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "destroy", params);
    },
  };
}

// Use this object to test and deploy the contract
export const ShinyToken = new Factory(
  Contract.fromJson(
    ShinyTokenContractJson,
    "",
    "5fa5fb7f1345ae13a578f49e9ddced90971c0ca97b6e0bf1ab17e64418d09ea5"
  )
);

// Use this class to interact with the blockchain
export class ShinyTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ShinyTokenTypes.State> {
    return fetchContractState(ShinyToken, this);
  }

  methods = {
    getSymbol: async (
      params?: ShinyTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<ShinyTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        ShinyToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: ShinyTokenTypes.CallMethodParams<"getName">
    ): Promise<ShinyTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        ShinyToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: ShinyTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<ShinyTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        ShinyToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: ShinyTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<ShinyTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        ShinyToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends ShinyTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<ShinyTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      ShinyToken,
      this,
      calls,
      getContractByCodeHash
    )) as ShinyTokenTypes.MultiCallResults<Calls>;
  }
}
